# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atadok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Átadók',
            },
        ),
        migrations.CreateModel(
            name='Megyek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megye', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Megyék',
            },
        ),
        migrations.CreateModel(
            name='Szabalyozok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azonosito', models.CharField(max_length=10)),
                ('grass_az', models.CharField(blank=True, max_length=10, null=True)),
                ('hrsz', models.CharField(blank=True, max_length=10, null=True)),
                ('letesites_ev', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('gps_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('gps_long', models.CharField(blank=True, max_length=20, null=True)),
                ('allomas_nev', models.CharField(max_length=255)),
                ('aktiv', models.BooleanField()),
                ('kivitel', models.CharField(choices=[('1_ag', '1 ágas'), ('2_ag', '2 ágas')], max_length=20)),
                ('elhelyezes', models.CharField(choices=[('akna', 'Akna'), ('epulet', 'Épület'), ('szekreny', 'Szekrény')], max_length=20)),
                ('funkcio', models.CharField(blank=True, choices=[('fogado', 'Fogadó'), ('korzeti', 'Körzeti'), ('ipari', 'Ipari'), ('egyedi', 'Egyedi')], max_length=20, null=True)),
                ('tulajdonjog', models.CharField(choices=[('zrt', 'Tigáz Zrt'), ('dso', 'Tigáz DSO'), ('idegen', 'Idegen')], max_length=20)),
                ('tulajdonos', models.CharField(blank=True, max_length=255, null=True)),
                ('eszkozszam', models.CharField(max_length=30)),
                ('beruhazasi_szam', models.CharField(max_length=30)),
                ('megjegyzes', models.CharField(blank=True, max_length=255, null=True)),
                ('nev_prim_nyom', models.DecimalField(decimal_places=3, max_digits=5)),
                ('nev_sek_nyom', models.DecimalField(decimal_places=3, max_digits=5)),
                ('uz_prim_nyom', models.DecimalField(decimal_places=3, max_digits=5)),
                ('uz_sek_nyom', models.DecimalField(decimal_places=3, max_digits=5)),
                ('nev_kapacitas', models.PositiveIntegerField(blank=True, null=True)),
                ('nyom_din_rendszer', models.BooleanField()),
                ('futott', models.BooleanField()),
                ('felugyeleti_rendszer', models.BooleanField()),
                ('rb_zona', models.CharField(choices=[('zona_1', 'Zóna 1'), ('zona_2', 'Zóna 2')], max_length=20)),
                ('sap_pm_az', models.CharField(blank=True, max_length=20, null=True)),
                ('telepites_ev', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('villamvedelem', models.CharField(choices=[('norma', 'Norma szerinti'), ('nem_norma', 'Nem norma szerinti')], max_length=30)),
                ('villamvedelem_ev', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('villamvedelem_kov_ev', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('karbantartas_2ev', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('karbantartas_10ev', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('osszedolg_szab', models.CharField(blank=True, max_length=255, null=True)),
                ('atado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Atadok')),
            ],
            options={
                'verbose_name_plural': 'Szabályozók',
            },
        ),
        migrations.CreateModel(
            name='Tartozekfajta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartozekfajta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tartozékfajták',
            },
        ),
        migrations.CreateModel(
            name='Tartozekgyartok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartozekgyarto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tartozékgyártók',
            },
        ),
        migrations.CreateModel(
            name='TartozekKi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beszereles_datum', models.DateField()),
                ('kiszereles_datum', models.DateField()),
                ('megjegyzes', models.CharField(blank=True, max_length=100, null=True)),
                ('szabalyozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Szabalyozok')),
            ],
            options={
                'verbose_name_plural': 'Tartozék kiszerelés',
            },
        ),
        migrations.CreateModel(
            name='Tartozekok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elhelyezkedes', models.CharField(choices=[('P1_ag', 'P1 ág'), ('P2_ag', 'P2 ág')], max_length=20)),
                ('beuzemeles_ev', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('beszereles_datum', models.DateField()),
                ('megjegyzes', models.CharField(blank=True, max_length=100, null=True)),
                ('szabalyozo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Szabalyozok')),
                ('tartozekfajta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Tartozekfajta')),
                ('tartozekgyarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Tartozekgyartok')),
            ],
            options={
                'verbose_name_plural': 'Tartozékok',
            },
        ),
        migrations.CreateModel(
            name='Tartozektipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartozektipus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tartozéktípusok',
            },
        ),
        migrations.CreateModel(
            name='Telepulesek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telepules', models.CharField(max_length=100)),
                ('telepules_kod', models.CharField(max_length=4)),
                ('megye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Megyek')),
            ],
            options={
                'verbose_name_plural': 'Települések',
            },
        ),
        migrations.CreateModel(
            name='Uzemek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzem', models.CharField(max_length=100)),
                ('terulet', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Üzemek',
            },
        ),
        migrations.AddField(
            model_name='telepulesek',
            name='uzem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Uzemek'),
        ),
        migrations.AddField(
            model_name='tartozekok',
            name='tartozektipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Tartozektipus'),
        ),
        migrations.AddField(
            model_name='tartozekki',
            name='tartozek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Tartozekok'),
        ),
        migrations.AddField(
            model_name='szabalyozok',
            name='ellatotttelepules',
            field=models.ManyToManyField(related_name='elltelep', related_query_name='elltelepquery', to='szabalyozok.Telepulesek'),
        ),
        migrations.AddField(
            model_name='szabalyozok',
            name='szabgyarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szab_gyarto', to='szabalyozok.Tartozekgyartok'),
        ),
        migrations.AddField(
            model_name='szabalyozok',
            name='telepules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szabalyozo_hely', to='szabalyozok.Telepulesek'),
        ),
    ]
