# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tartozekki',
            name='beszereles_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tartozekki',
            name='kiszereles_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tartozekki',
            name='szabalyozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Szabalyozok'),
        ),
        migrations.AlterField(
            model_name='tartozekki',
            name='tartozek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Tartozekok'),
        ),
    ]
