# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0003_auto_20170109_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tartozekki',
            name='szabalyozo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tartki_szab', to='szabalyozok.Szabalyozok'),
        ),
        migrations.AlterField(
            model_name='tartozekki',
            name='tartozek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tartki', to='szabalyozok.Tartozekok'),
        ),
    ]
