# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0004_auto_20170109_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TartozekKi',
            new_name='Tartozekkiszerel',
        ),
        migrations.AlterField(
            model_name='tartozekok',
            name='tartozekgyarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Tartozekgyartok'),
        ),
    ]
