# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0005_auto_20170109_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muszerek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elhelyezkedes', models.CharField(choices=[('P1_ag', 'P1 ág'), ('P2_ag', 'P2 ág')], max_length=20)),
                ('beszereles_datum', models.DateField()),
                ('selejt', models.BooleanField()),
                ('gyariszam', models.CharField(max_length=50)),
                ('gyartas_ev', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('mereshatar1', models.CharField(blank=True, max_length=20, null=True)),
                ('mereshatar2', models.CharField(blank=True, max_length=20, null=True)),
                ('osztalypontossag', models.CharField(blank=True, max_length=20, null=True)),
                ('kalib_ciklusido', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('kalib_datum', models.DateField()),
                ('kov_kalib_datum', models.DateField()),
                ('megjegyzes', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Műszerek',
            },
        ),
        migrations.CreateModel(
            name='Muszerfajta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muszerfajta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Műszerfajták',
            },
        ),
        migrations.CreateModel(
            name='Muszergyarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muszergyarto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Műszergyártók',
            },
        ),
        migrations.CreateModel(
            name='Muszerkiszerel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beszereles_datum', models.DateField(blank=True, null=True)),
                ('kiszereles_datum', models.DateField(blank=True, null=True)),
                ('megjegyzes', models.CharField(blank=True, max_length=100, null=True)),
                ('muszer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muszerki', to='szabalyozok.Muszerek')),
                ('szabalyozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muszerki_szab', to='szabalyozok.Szabalyozok')),
            ],
            options={
                'verbose_name_plural': 'Műszer kiszerelés',
            },
        ),
        migrations.CreateModel(
            name='Muszertipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muszertipus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Műszertípusok',
            },
        ),
        migrations.AddField(
            model_name='muszerek',
            name='muszerfajta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muszer_fajta', to='szabalyozok.Muszerfajta'),
        ),
        migrations.AddField(
            model_name='muszerek',
            name='muszergyarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Muszergyarto'),
        ),
        migrations.AddField(
            model_name='muszerek',
            name='muszertipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Muszertipus'),
        ),
        migrations.AddField(
            model_name='muszerek',
            name='szabalyozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Szabalyozok'),
        ),
    ]
