# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0006_auto_20170112_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muszerek',
            name='kalib_ciklusido',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='muszerek',
            name='kalib_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muszerek',
            name='kov_kalib_datum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
