# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0007_auto_20170112_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muszerek',
            name='beszereles_datum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
