# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0008_auto_20170112_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muszermunkak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muszmunka_datum', models.DateField()),
                ('megjegyzes', models.CharField(blank=True, max_length=100, null=True)),
                ('muszer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Muszerek')),
            ],
            options={
                'verbose_name_plural': 'Műszer munkák',
            },
        ),
        migrations.CreateModel(
            name='MuszerMunkatipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muszermunkatipus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Műszer munkatípusok',
            },
        ),
        migrations.CreateModel(
            name='Szabalyozomunkak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szabmunka_datum', models.DateField()),
                ('megjegyzes', models.CharField(blank=True, max_length=100, null=True)),
                ('szabalyozo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Szabalyozok')),
            ],
            options={
                'verbose_name_plural': 'Szabályozó munkák',
            },
        ),
        migrations.CreateModel(
            name='SzabalyozoMunkatipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szabalyozomunkatipus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Szabályozó munkatípusok',
            },
        ),
        migrations.AddField(
            model_name='szabalyozomunkak',
            name='szabalyozomunkatipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szabmunka_tipus', to='szabalyozok.SzabalyozoMunkatipus'),
        ),
        migrations.AddField(
            model_name='muszermunkak',
            name='muszermunkatipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szabmunka_tipus', to='szabalyozok.SzabalyozoMunkatipus'),
        ),
    ]
