# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0009_auto_20170113_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muszermunkak',
            name='muszermunkatipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muszermunka_tipus', to='szabalyozok.MuszerMunkatipus'),
        ),
    ]
