# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import szabalyozok.models.DocModel


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0010_auto_20170113_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctipus', models.CharField(max_length=10)),
                ('doc_nev', models.CharField(max_length=100)),
                ('eszkoz_id', models.IntegerField()),
                ('felt_datum', models.DateField()),
                ('docfile', models.FileField(upload_to=szabalyozok.models.DocModel.content_file_name)),
            ],
            options={
                'verbose_name_plural': 'Dokumentumok',
            },
        ),
    ]
