# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0012_muszerkiszerel_selejt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_nev', models.CharField(max_length=100)),
                ('image', stdimage.models.StdImageField(upload_to='content_file_name')),
            ],
            options={
                'verbose_name_plural': 'Képek',
            },
        ),
    ]
