# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import szabalyozok.models.DocModel


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0013_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='szabalyozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Szabalyozok'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=stdimage.models.StdImageField(upload_to=szabalyozok.models.DocModel.content_kep_name),
        ),
    ]
