# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 08:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0014_auto_20170116_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szabalyozok',
            name='funkcio',
            field=models.CharField(blank=True, choices=[('', 'Kérem válasszon'), ('fogado', 'Fogadó'), ('korzeti', 'Körzeti'), ('ipari', 'Ipari'), ('egyedi', 'Egyedi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='karbantartas_10ev',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='karbantartas_2ev',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='rb_zona',
            field=models.CharField(blank=True, choices=[('zona_1', 'Zóna 1'), ('zona_2', 'Zóna 2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='szabgyarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='szab_gyarto', to='szabalyozok.Tartozekgyartok'),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='telepites_ev',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='villamvedelem',
            field=models.CharField(blank=True, choices=[('norma', 'Norma szerinti'), ('nem_norma', 'Nem norma szerinti')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='villamvedelem_ev',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='villamvedelem_kov_ev',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
