# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0015_auto_20170127_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szabalyozok',
            name='elhelyezes',
            field=models.CharField(choices=[('akna', 'Akna'), ('epulet', 'Épület'), ('szekreny', 'Szekrény')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='funkcio',
            field=models.CharField(choices=[('', 'Kérem válasszon'), ('fogado', 'Fogadó'), ('korzeti', 'Körzeti'), ('ipari', 'Ipari'), ('egyedi', 'Egyedi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='kivitel',
            field=models.CharField(choices=[('1_ag', '1 ágas'), ('2_ag', '2 ágas')], max_length=20, null=True),
        ),
    ]
