# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0016_auto_20170127_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosztika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_nyomas', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('p2_nyomas', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('p1_also_nyomas', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('p2_felso_nyomas', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('biztlef_nyomas', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('diag_datum', models.DateField()),
                ('megjegyzes', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnosztika',
            },
        ),
        migrations.CreateModel(
            name='DiagnosztikaOk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosztikaok', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Diagnosztika oka',
            },
        ),
        migrations.CreateModel(
            name='EllenorzesiCiklus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ellenorzesiciklus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ellenőrzési ciklus',
            },
        ),
        migrations.CreateModel(
            name='SzabKarb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szabkarb', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Szab. karbantartó',
            },
        ),
        migrations.CreateModel(
            name='SzabVezerlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szabvezerles', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Szab. vezérlés módja',
            },
        ),
        migrations.AddField(
            model_name='szabalyozok',
            name='burkolt_terulet',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='szabalyozok',
            name='fuves_terulet',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='szabalyozok',
            name='ossz_terulet',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='tartozekok',
            name='gyariszam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='muszerek',
            name='elhelyezkedes',
            field=models.CharField(choices=[('', 'Kérem válasszon'), ('p1_ag', 'P1 ág'), ('p2_ag', 'P2 ág'), ('kozos', 'Közös')], max_length=20),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='elhelyezes',
            field=models.CharField(choices=[('', 'Kérem válasszon'), ('akna', 'Akna'), ('epulet', 'Épület'), ('szekreny', 'Szekrény')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='kivitel',
            field=models.CharField(choices=[('', 'Kérem válasszon'), ('1_ag', '1 ágas'), ('2_ag', '2 ágas')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='rb_zona',
            field=models.CharField(blank=True, choices=[('', 'Kérem válasszon'), ('zona_1', 'Zóna 1'), ('zona_2', 'Zóna 2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='tulajdonjog',
            field=models.CharField(choices=[('', 'Kérem válasszon'), ('zrt', 'Tigáz Zrt'), ('dso', 'Tigáz DSO'), ('idegen', 'Idegen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='szabalyozok',
            name='villamvedelem',
            field=models.CharField(blank=True, choices=[('', 'Kérem válasszon'), ('norma', 'Norma szerinti'), ('nem_norma', 'Nem norma szerinti')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tartozekok',
            name='elhelyezkedes',
            field=models.CharField(choices=[('', 'Kérem válasszon'), ('p1_ag', 'P1 ág'), ('p2_ag', 'P2 ág'), ('kozos', 'Közös')], max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosztika',
            name='diagnosztikaok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.DiagnosztikaOk'),
        ),
        migrations.AddField(
            model_name='diagnosztika',
            name='szabalyozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.Szabalyozok'),
        ),
        migrations.AddField(
            model_name='szabalyozok',
            name='ellenorzesiciklus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ellen_ciklus', to='szabalyozok.EllenorzesiCiklus'),
        ),
        migrations.AddField(
            model_name='szabalyozok',
            name='szabkarb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='szab_karb', to='szabalyozok.SzabKarb'),
        ),
        migrations.AddField(
            model_name='tartozekok',
            name='szab_vezerles_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='szabalyozok.SzabVezerlesModel'),
        ),
    ]
