# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyozok', '0018_auto_20170127_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szabalyozok',
            name='uz_prim_nyom',
        ),
        migrations.RemoveField(
            model_name='szabalyozok',
            name='uz_sek_nyom',
        ),
    ]
